<div class="centertext">
	<h1>Kodowanie i grafika:</h1>
	<img src="/img/miny.gif" hspace="10" width="63" height="138" class="float-left" alt="Andrzej Mazur">
	<img src="/img/amflaga.gif" width="51" height="51" class="float-right"><strong>Andrzej Mazur</strong><br>
	EZNAWCA (AMPartner)<br>
	55-200 Oława<br>
	WWW: <a href="https://eznawca.pl/" target="_blank" class="ext"><span>https://</span>eznawca.pl<svg><use xlink:href="#external"></svg></a><br>
	<br style="clear: both">
	<br>

	<a href="https://eznawca.pl/" target="_blank" title="Andrzej Mazur EZNAWCA - programista PHP"><img src="/img/ampartne.gif" width="38" height="31" class="icoext" alt="eznawca.pl"><strong>EZNAWCA.pl</strong></a> - Andrzej Mazur - programista PHP</a><br>
	<br>
	<a href="https://www.facebook.com/OlawaTwojeMiasto/" target="_blank" title="Oława Twoje Miasto - Internetowy informator miasta Oławy"><img src="/img/olawa.gif" width="33" height="36" class="icoext" alt="FB.com/OlawaTwojeMiasto"><strong>Oława Twoje Miasto</strong></a> - Internetowy informator miasta Oławy</a><br>

	<h1>Współautorzy:</h1>
	<h2>Treść i materiały dydaktyczne</h2>
	dr Maria Kruk<br>
	Andrzej Domaradzki<br>
	Andrzej Mazur<br>
	Paweł Grabowski<br>

	<h2>Weryfikacja materiałów</h2>
	dr Maria Kruk<br>
	Joanna Dudek<br>
	Anna Gadomska<br>
	Andrzej Mazur<br>

	<h2>Animacje</h2>
	Sylwester Gigoń<br>
	Andrzej Kukuła<br>
	Dawid Kliszewski<br>
	Wojciech Pukocz<br>

	<h2>Oprawa dźwiękowa</h2>
	Radosław Szamrej<br>
	Adam Skorupa<br>

	<h2>Głosy</h2>
	Danuta Dudek<br>
	Mirella Pempko<br>
	Anna Mazur<br>

	<h2>Konsultacje</h2>
	Zespół nauczycieli matematyki<br>
	Kuratorium Oświaty we Wrocławiu<br>

	<h2>Producent</h2>
	FATERBIT A.P.H.<br>
	Marcin Dudek<br>
	tel. (0-71) 3134108<br>
	e-mail: <u>biuro@faterbit.com.pl</u><br>
	e-mail: <u>faterbit@polbox.com</u><br>
	<h2>Wyłączny dystrybutor</h2>
	JONASOFT<br>

</div>

