#Figury płaskie i przestrzenne - Prezentacja trójwymiarowa

<div class="centertext">
<h1>Figury płaskie i przestrzenne 3D</h1>
<p>Animacja figur. Prezentacja trójwymiarowa.</p>
<div align="center"><img alt="Figur - prezentacja trójwymiarowa 3D" src="/img/ekrfig3d.gif"></div>
<a href="/?id=mapa2" title="Wstecz"><img src="/img/wstecz.gif" alt="Wstecz" width="35" height="17" class="icoprog">Wstecz</a>
</div>