#Grafmat Junior - Program do robienia wykresów funkcji

<div class="centertext">
<h1>GrafMat Junior</h1>
<p>Moduł do wizualizacji wykresów funkcji matematycznych. Dzieki niemu możemy wyświetlić do pięciu funkcji równocześnie na jednym układzie współrzędnych. Może służyć do poznawania zmienności funkcji, rozwiązywania równań metodą graficzną jak i wielu innych rzeczy.</p>
<div align="center"><img alt="GrafMat - wizualizacji wykresów funkcji" src="/img/ekrgrafm.gif"></div>
<a href="/?id=mapa2" title="Wstecz"><img src="/img/wstecz.gif" alt="Wstecz" width="35" height="17" class="icoprog">Wstecz</a>
</div>