#Opcje programu Matematyk - Kolory, ustawienia programu, dźwięk, drukarka, pulpit, klawiatura

<div class="centertext">
<h1>Opcje programu</h1>
<h2>Ustawienia programu. Kolory. Opcje Matematyka</h2>
<br>
<div align="center"><img alt="Opcje programu" src="/img/ekropcje.gif"></div>
<a href="/?id=mapa2" title="Wstecz"><img src="/img/wstecz.gif" alt="Wstecz" width="35" height="17" class="icoprog">Wstecz</a>
</div>