#Elementy - Najciekawsze moduły, opcje i funkcje programu Matematyk

<div class="centertext">
	<h1>Elementy - Najciekawsze moduły, opcje i funkcje</h1>
	<img src="/img/mowa.gif" width="74" height="99" class="float-left">
	<img src="/img/amflaga.gif" width="51" height="51" class="float-right">

	<p>W programie Matematyk, oprócz podstawowego sposobu pracy, obsługiwanego przez główne przyciski,</p>

	<p class="center"><a href="/?id=mapa"><img src="/img/ekrmain.gif" alt="Matematyk - główne przyciski" width="317" height="372"></a></p>

	<p>(o czym szerzej na stronie <a href="/?id=start"><strong>Rozpocznij pracę z programem</strong></a>), znajduje
	się wiele ciekawych podprogramów spełniających funkcje, <em>uzupełniające</em> i <em>rozszerzające</em>
	materiał zawarty w głównej części programu. Pozwalają one w nieco bardziej <em>zabawowy</em> sposób
	zapoznawać się z matematyką. Dostęp do tych funkcji realizowany jest przez następujące przyciski:</p>

	<p class="center"><img src="/img/ekreleme.gif" alt="Najciekawsze moduły, podprogramy" width="416" height="103"></p>

	<p class=glowamain >Moduły matematyka:</p>

	<!-- kotwica -->
	<a name="idk_kalkulator"></a>
	<p><img src="/img/icokalk.gif" alt="" width="25" height="29" class="icoprog"> <strong>Kalkulator</strong>. Pod
	tym jednym przyciskiem kryją się dwa kalkulatory: jeden
	prosty do podstawowych działań matematycznych, </p>

	<p class="center"><img src="/img/ekrkalk1.gif" width="184" height="230" alt="Kalkulator podstawowy"></p>

	<p>drugi dużo bardziej złożony - inżynierski, który pozwala wykonać bardzo dużo
	złożonych funkcji.</p>

	<p class="center"><img src="/img/ekrkalk2.gif" width="226" height="331" alt="Kalkulator inżynierski"></p>

	<!-- kotwica -->
	<a name="idk_grafmat"></a>
	<p><img src="/img/icografm.gif" alt="" width="32" height="28" class="icoprog"> <strong>GrafMat Junior</strong>, to moduł do wizualizacji funkcji
	matematycznych. Pozwala wyświetlić do pięciu funkcji
	równocześnie na jednym wykresie. Może służyć do
	poznawania zmienności funkcji, rozwiązywania równań
	metodą graficzną jak i wielu jeszcze innych rzeczy.</p>

	<p class="center">
	<a href="/?id=ekrgrafm"><img src="/img/ekrgmat.gif" alt="GrafMat wykresy funkcji matematycznych" width="404" height="327"></a>
	</p>

	<!-- kotwica -->
	<a name="idk_figury3d"></a>
	<p><img src="/img/icofig3d.gif" alt="" width="27" height="28" class="icoprog"> <strong>Figury</strong>.
	Przestrzenna prezentacja figur płaskich i przestrzennych (stereometrycznych), z możliwością ich obrotu w każdym z trzech wymiarów.</p>

	<p class="center">
	<a href="/?id=ekrfig3d"><img src="/img/ekrfig3e.gif" alt="Przestrzenna prezentacja figur" width="367" height="395"></a>
	</p>

	<p>Dodatkowo można przełączyć się na prawdziwie trójwymiarowy widok, oglądany za pomocą okularów 3D.</p>

	<p class="center"><img src="/img/okular3d.gif" alt="Okulary 3D" width="325" height="166"></p>

	<!-- kotwica -->
	<a name="idk_kreator"></a>
	<p><strong><img src="/img/icokreat.gif" alt="" width="28" height="29" class="icoprog"> Kreator</strong>.
	Dzięki temu modułowi możesz wędrować przez świat figur geometrycznych. Program zapyta Cię o ilość
	boków, rodzaje podstaw i wiele jeszcze innych rzeczy. A na tej podstawie, krok po kroku powstanie Twoja
	wymyślona figura geometryczna.</p>

	<p class="center">
	<a href="/?id=ekrkreat"><img src="/img/ekrkreae.gif" alt="Kreator figur geometrycznych" width="368" height="300"></a>
	</p>

	<!-- kotwica -->
	<a name="idk_wzory"></a>
	<p><img src="/img/icowzory.gif" alt="" width="28" height="28" class="icoprog"> <strong>Wzory, definicje i tablice matematyczne</strong>
	Moduł zawiera kompletny podręcznik do matematyki, ułożony w hierarchiczny sposób na wzór spisu treści. Zawiera także
	najważniejsze tablice matematyczne.</p>

	<p class="center">
	<a href="/?id=ekrwzory"><img src="/img/ekrwzore.gif" alt="Wzory definicje i tablice matematyczne" width="383" height="215"></a>
	</p>

	<!-- kotwica -->
	<a name="idk_katy"></a>
	<p><img src="/img/icokaty.gif" alt="" width="28" height="24" class="icoprog"> <strong>Kąty</strong>.
	Moduł za pomocą którego zapoznamy się z pojęciem kąta, a także z ich typami i rodzajami. Bez kątów nie
	istnieją funkcje trygonometryczne, których związek z kątami poznasz także w module kąty.</p>

	<p class="center">
	<a href="/?id=ekrkaty"><img src="/img/ekrkatye.gif" alt="Kąty - funkcje trygonometryczne" width="383" height="328"></a>
	</p>

	<!-- kotwica -->
	<a name="idk_rachmistrz"></a>
	<p><img src="/img/icorachm.gif" alt="" width="27" height="23" class="icoprog"> <strong>Rachmistrz</strong>.
	Za pomocą tego modułu szybko rozwiążesz każde zadanie z geometrii i większość innych zadań
	domowych. Program podzielony jest na części, w których każda umożliwia rozwiązanie określonego typu zadań.</p>

	<p class="center">
	<a href="/?id=ekrrachm"><img src="/img/ekrrache.gif" alt="Rachmistrz - rozwiązywanie zadań domowych" width="301" height="298"></a>
	</p>

	<p class="center">
	<img src="/img/kulnieb.gif" hspace="10" width="12" height="12" alt="">
	<img src="/img/kulnieb.gif" hspace="10" width="12" height="12" alt="">
	<img src="/img/kulnieb.gif" hspace="10" width="12" height="12" alt=""></p>

	<p>Jeżeli chcesz dokładniej zapoznać się z wyglądem programu Matematyk, zapraszam Cię na strony <a href="/?id=mapa"><strong>Mapa programu</strong></a>.
	Znajdziesz tam przedstawione wszystkie ważniejsze okienka, a sposób ich wyświetlania wzorowany jest na działaniu samego programu - co da Ci większe
	wyobrażenie na temat działania programu Matematyk.</p>
</div>