<div class="centertext">
	<img src="/img/amflaga.gif" alt="Andrzej ENZAWCA Mazur (AMPartner)" width="51" height="51" class="float-right">
	<h1>Uruchomienie i instalacja programu</h1>

	<p>Dla uruchomienia programu Matematyk, nie jest wymagana żadna instalacja.
	Program pracuje bezpośrednio z płyty, natychmiast po uruchomieniu go za
	pomocą pliku <span>START.BAT</span>.</p>


	<h2>Windows 95/98/2000</h2>
	<p>W środowisku Windows 95/98/2000 program Matematyk uruchamia się
	automatycznie po włożeniu płyty <span>CDROM</span> do czytnika. Po czym
	od razu gotowy jest do pracy.</p>

	<p>Aby uruchomić program po raz kolejny należy podwójnie
	kliknąć na ikonie CDROM, w folderze <span>Mój komputer</span>, lub
	otworzyć i zamknąć szufladę z płytą <span>CDROM</span>.</p>


	<h2>Dos</h2>
	<p>W środowisku DOS przejdź na swój <span>dysk CDROM</span> np: D:, i
	napisz <span>START</span>, uruchomisz w ten sposób program Matematyk.</p>

	<p>Możesz także posłużyć się programem <span>Norton Commander</span>
	(lub podobnym) do uruchomienia programu. Zmieniając dysk na
	<span>CDROM</span> np. <span>Atl+F1</span> i uruchamiając plik <span>START.BAT</span>.</p>


	<h2>Windows 3.1x</h2>
	<p>W środowisku Windows 3.1x najszybciej uruchomisz program
	wybierając w programie <span>Menadżer Programów</span> z menu <span>Plik</span>
	opcję <span>Uruchom...</span> i wpisując: <span>D:\START.BAT (D: - właściwa litera
	dysku twojego CDROM'a)</span>. Możesz także posłużyć się
	programem <span>Menadżer Plików</span> podobnie jak <span>Norton'em
	Commander'em</span>.</p>
	<p><b>Uwaga:</b></p>
	<ul class="mini">
	   <li>Program nie modyfikuje plików <span>AUTOEXEC.BAT</span> i <span>CONFIG.SYS</span>,</li>
	   <li>Program nie wpisuje swoich ustawień do Rejestrów
	   Windows, ani do żadnych plików .INI.</li>
	   <li>Program podczas pracy zapisuje maleńkie zbiory <span>(ok. 1KB)</span>
	   na dysk <span>C:</span>. Zbiory te nie przyrastają i nie zaśmiecają
	   dysku twardego.</li>
	</ul>
	<p>Dlatego też nie trzeba programu odinstalowywać jeżeli się
	więcej go nie używa. Mimo to, jeżeli nie będziesz więcej używał programu
	Matematyk możesz wykonać oczyszczenie dysku twardego z
	tymczasowych plików programu Matematyk uruchamiając
	program <span>UnInstal</span> za pomocą pliku <span>UNINS.BAT</span>.</p>
</div>
