#Andrzej EZNAWCA Mazur prezentuje program: Matematyk

<div class="centertext" style="max-width: 700px">
	<h1><span>Andrzej Mazur EZNAWCA</span> prezentuje program <span>Matematyk</span></h1>
	<figure class="float-left">
		<a href="/?id=start" title="Rozpocznij pracę z programem"><img src="/img/wstep.gif" alt="Rozpocznij pracę z programem" width="212" height="124"></a>
		<figcaption>Elementy - Najciekawsze moduły, opcje i funkcje</figcaption>
	</figure>

	<figure class="float-right" style="margin-top: 5px">
		<a href="/?id=mapa"><img src="/img/main.gif" alt="Mapa programu" width="458" height="309"></a>
		<figcaption>Mapa programu - wygląd programu Matematyk i jego poszczególnych modułów</figcaption>
	</figure>
	
</div>