#Mapa programu - tu możesz zapoznać się z wyglądem i działaniem programu Matematyk

<div class="centertext" style="max-width: 700px">
	<a href="/?id=mapa2"><img src="/img/mapalogo.gif" alt="Mapa programu" width="305" height="245" style="float: right; margin-left: 15px"></a>

	<h1>Mapa programu</h1>
	<p>
	Na stronach <strong>mapa programu</strong> możesz zapoznać się z
	wyglądem programu <em>Matematyk</em> i jego poszczególnych
	modułów. Obsługa niniejszej prezentacji, wzorowana jest na
	obsłudze samego programu. Klikając na odpowiednie ikony,
	wyświetlane są odpowiednie okienka podprogramów. Naciskając
	guzik <em>Wstecz</em> wracamy do głównego okna programu.
	Wszystkie okienka zostały przedstawione w oryginalnej
	wielkości.</p>

	<p>Wszystkie następne strony
	oparte są na dużo wymiarowej grafice, przez co ich wczytywanie
	może być długotrwałe. Jeżeli to Cię nie przeraża, bardzo
	zapraszam do obejrzenia niniejszej prezentacji.<strong> </strong><a
	href="/?id=mapa2"><strong>Wejście</strong></a></p>
</div>