#Główny pulpit programu Matematyk

<div class="centertext">
<h1>Główne okno programu Matematyk</h1>
<p>Kliknij w wybraną ikonę aby zobaczyć moduł programu.</p>
<img src="/img/mapekran.gif" width="622" height="438" vspace="5" usemap="#mapaekranu" class="shadow">
</div>

<map name="mapaekranu">
   <area shape=rect coords="4, 24, 47, 67" href="/?id=ekrstart" alt="Start - zacznij naukę" title="Start - czyli zacznij naukę">
   <area shape=rect coords="48, 24, 91, 67" href="/?id=ekrtesty" alt="Testy i egzaminy sprawdzające" title="Testy i egzaminy sprawdzające">
   <area shape=rect coords="92, 24, 135, 67" href="/?id=ekrocena" alt="Dzienniczek ucznia oceny" title="Dzienniczek ucznia - oceny">
   <area shape=rect coords="150, 24, 193, 67 " href="/?id=ekrkalk" alt="Kalkulatory" title="Kalkulatory - prosty i inżynierski">
   <area shape=rect coords="194, 24, 237, 67" href="/?id=ekrgrafm" alt="GrafMat Junior - wykresy funkcji" title="GrafMat Junior - wizualizacja wykresów funkcji">
   <area shape=rect coords="238, 24, 281 ,67" href="/?id=ekrfig3d" alt="Figury płaskie i przestrzenne" title="Figury płaskie i przestrzenne 3D">
   <area shape=rect coords="282 ,24, 325, 67" href="/?id=ekrkreat" alt="Kreator figur" title="Kreator figur">
   <area shape=rect coords="326 ,24, 369, 67" href="/?id=ekrwzory" alt="Wzory definicje i tablice" title="Wzory definicje i tablice matematyczne">
   <area shape=rect coords="370 ,24, 413, 67" href="/?id=ekrkaty" alt="Kątomierz - nauka kątów" title="Kątomierz nauka kątów">
   <area shape=rect coords="428 ,24, 471, 67" href="/?id=ekrrachm" alt="Rachmistrz rozwiązywanie zadań" title="Rachmistrz rozwiązywanie zadań">
   <area shape=rect coords="486 ,24, 529, 67" href="/?id=ekropcje" alt="Opcje programu" title="Opcje programu">
   <area shape=rect coords="530 ,24, 573, 67" href="/?id=ekrpomoc" alt="Pomoc programu" title="Tematy pomocy">
   <area shape=rect coords="574 ,24, 617, 67" href="/?id=main" alt="Wyjście" title="Wyjście">
   <!-- Dolna czesc ikon... -->
   <area shape=rect coords="4 ,391, 135, 434" href="/?id=ekrzadpp" alt="Koniec lekcji" title="Koniec lekcji - udzielanie odpowiedzi w pigułce">
   <area shape=rect coords="136 ,391, 223, 434" href="/?id=ekrponas" alt="Dzienniczek" title="Koniec lekcji - dzienniczek">
   <area shape=rect coords="224 ,391, 267, 434" href="/?id=ekrdruk" alt="Drukowanie i drukarka" title="Drukowanie i drukarka">
   <area shape=rect coords="266 ,391, 329, 434" href="/?id=ekrcieka" alt="Ciekawostki - iluzja wzroku" title="Ciekawostki - Iluzja wzroku, nieprawdziwe figury">
   <area shape=rect coords="6 ,70 615, 387" href="/?id=ekrsrode" alt="Lekcje i rozwiązywanie zadań" title="Lekcje i rozwiązywanie zadań">
</map>

