#Dla nauczycieli - Program Matematyk jest bardzo pomocny w pracy nauczyciela, tak przy prowadzeniu lekcji, jak i indywidualnej pracy z uczniem

<div class="centertext">
	<img src="/img/nauczlog.gif" alt="" width="59" height="52" class="float-left">
	<img src="/img/amflaga.gif" alt="Andrzej ENZAWCA Mazur (AMPartner)" width="51" height="51" class="float-right">
	<h1>Dla nauczycieli</h1>
	<p>Program <em>Matematyk</em> może być bardzo pomocny w pracy <strong>nauczyciela</strong>, tak przy prowadzeniu lekcji, jak i indywidualnej pracy z uczniem.
	W kilku słowach pragnę przedstawić najważniejsze cechy programu przydatne nauczycielom.</p>
	<ul class="mini">
		<li>Możliwość monitorowania postępu w nauce, każdego korzystającego z programu ucznia (program przechowuje dane każdego ucznia z osobna).
		<li>Moduł wykresu <a href="/?id=elementy#idk_grafmat">GrafMat</a> zastępuje tablicę szkolną, podczas rysowania wszelkiego rodzaju wykresów funkcji.
		<li>Szybki dostęp do pomocy matematycznych takich jak np. <a href="/?id=elementy#idk_katy">kątomierz</a>
		<li>Wygodny i poręczny <a href="/?id=elementy#idk_kalkulator">kalkulator</a> prosty jak i zaawansowany dla inżynierów.
		<li>Niewygórowane <a href="/?id=system">wymagania sprzętowe</a> (środowisko DOS) umożliwiają Ci pracę na <strong>każdym</strong> sprzęcie.
		<li>W program wbudowany jest pełny, rozszerzony <a href="/?id=elementy#idk_wzory">podręcznik do matematyki</a>, uzupełniony ilustracjami, prezentacjami multimedialnymi i przykładowymi zadaniami.
		<li>W szkole mamy możliwość pracy z programem w dowolnej z typów sieci - w pełni wystarczająca jest prosta, bez serwerowa (per-to-per) sieć, np. Windows 95(98). Program pracuje przy wykorzystaniu z jednej kopi programu, pracującej na komputerze z CDROM, pozostałe komputery uczniów nie muszą posiadać czytników CDROM.
	</ul>
	<p>Aby zobaczyć jak wyglądają poszczególne moduły programu i zapoznać się ze strukturą programu - zapraszam na strony <a href="/?id=mapa">Mapa programu</a>.
	Dla dokładniejszego zapoznania się z najciekawszymi elementami programu - zapraszam na strony <a href="/?id=elementy">Elementy - Najciekawsze moduły</a>. Szerzej o sposobie pracy z zdaniami i metodach
	sprawdzania wiadomości znajdziesz na stronie <a href="/?id=start">Rozpocznij pracę z programem</a>.</p>
</div>
