#Pomoc - najważniejsze cechy programu Matematyk. Środowisko, wymagania sprzętowo-programowe, instalacja programu

<div class="centertext">
	<img src="/img/ryspomoc.gif" alt="" width="80" height="74" class="float-left"
	<img src="/img/amflaga.gif" alt="Andrzej ENZAWCA Mazur (AMPartner)" width="51" height="51" class="float-right">
	<h1>Pomoc</h1>
	<p>Po krótce pragnę przedstawić najważniejsze cechy programu Matematyk:</p>
	<ul class="mini">
		<li>Praca w Środowisku DOS - niewygórowane
		wymagania <a href="/?id=system">sprzętowe.</a> Dzięki czemu możliwa
		jest praca na wszystkich komputerach, także tych słabszych - jakie
		spotykamy w naszych szkołach.</li>
		<li>Intuicyjna - prosta obsługa. W pełni konfigurowalne, okienkowe środowisko pracy
		wzorowane na systemie Windows.</li>
		<li>Bogata multimedialność: Dostępnych jest wiele animowanych prezentacji,
		przedstawiających świat matematyki.</li>
		<li>Wszechobecna pomoc dźwiękowa. Żadne miejsce czy okienko programu nie pozostawia
		Cię bez pomocy. Oprócz standardowego tekstu kryjącego się pod przyciskiem
		<em>Pomoc</em>, zawsze twój zaprzyjaźniony kolega <em>Arkadiusz</em> - miłym
		głosem, przystępnie wyjaśni Ci co należy zrobić i z czego możesz skorzystać.</li>
		<li>Uniwersalne zastosowanie:</li>
		<ul class=wciete>
			<li>Dla samodzielnej pracy ucznia z zadaniami - problemami.</li>
			<li>Elektroniczny <a href="/?id=elementy#idk_wzory">podręcznik</a> - w programie zawarty jest kompletny podręcznik
			do matematyki, rozszerzony o wiele ciekawych i różnorodnych problemów.</li>
			<li>Dla nauczycieli - <a href="/?id=start#idk_testy">Testy - sprawdzanie umiejętności</a> i wiadomości uczniów.</li>
			<li>Jako pomoc w rozwiązywaniu zadań domowych: <a href="/?id=elementy#idk_kalkulator">kalkulator</a>,
			<a href="/?id=elementy#idk_rachmistrz">rachmistrz</a>, <a href="/?id=elementy#idk_grafmat">wykresy funkcji</a>, <a href="/?id=elementy#idk_wzory">podręcznik - wzory, definicje</a>.</li>
		</ul>
	</ul>

	<p>Dla poznania najciekawszych modułów programu, zapraszam na
	strony <a href="/?id=elementy">Elementy - najciekawsze moduły</a>.</p>

	<p>Wszystkich zainteresowanych stroną <em>techniczną</em> programu,
	zapraszam pod następujące odsyłacze:</p>
	<ul class="mini">
		<li><a href="/?id=system">Wymagania sprzętowo-programowe,</a></li>
		<li><a href="/?id=instal">Instalacja programu</a></li>
	</ul>

	<p>Informacji o <em>merytorycznej</em> zawartości programu dostarczą strony:</p>
	<ul class="mini">
		<li><a href="/?id=naucz" title="Dla nauczycieli">Dla nauczycieli</a></li>
		<li><a href="/?id=start" title="Rozpocznij pracę z programem">Start - zawartość programu.</a></li>
	</ul>

	<p>Po pilotowej wersji programu <strong>1.0</strong> ukazała się już nowa ulepszona
		wersja <strong>2.0</strong>. Zapraszam wszystkich do poznania naszego programu
	i zanurzenia się w fascynujący świat matematyki.</p>

	<p class="float-right"><a href="/?id=autorzy"><strong><em>Autor - Andrzej Mazur</em></strong></a></p>
</div>

