#Spis treści czyli Mapa strony

<div class="centertext">
<h1 title="Mapa strony">Spis treści</h1>
<ul>
	<li><a href="/?id=autorzy" title="Autor - Andrzej Mazur">Autorzy programu</a>
	<li><a href="/?id=ekrcieka" title="Ciekawostki - iluzja wzroku">Ciekawostki - Iluzja wzroku, nieprawdziwe figury</a>
	<li><a href="/?id=ekrdruk" title="Ustawienia drukarki">Drukowanie i drukarka</a>
	<li><a href="/?id=ekrfig3d" title="Figury płaskie i przestrzenne">Przestrzenna prezentacja figur</a>
	<li><a href="/?id=ekrgrafm" title="GrafMat Junior - wykresy funkcji matematycznych">GrafMat Junior - wizualizacja wykresów funkcji</a>
	<li><a href="/?id=ekrkalk" title="Kalkulatory">Kalkulatory - prosty i inżynierski</a>
	<li><a href="/?id=ekrkaty" title="Kątomierz - nauka kątów i funkcje trygonometryczne">Kątomierz nauka kątów plus funkcje trygonometryczne</a>
	<li><a href="/?id=ekrkreat" title="Kreator figur">Kreator figur geometrycznych</a>
	<li><a href="/?id=ekrocena" title="Dzienniczek ucznia oceny">Dzienniczek ucznia - oceny</a>
	<li><a href="/?id=ekropcje" title="Opcje programu">Opcje programu</a>
	<li><a href="/?id=ekrpomoc" title="Pomoc programu">Tematy pomocy</a>
	<li><a href="/?id=ekrponas" title="Zakończenie lekcji - Dzienniczek">Zakończenie lekcji - dzienniczek</a>
	<li><a href="/?id=ekrrachm" title="Rachmistrz rozwiązywanie zadań">Rachmistrz rozwiązywanie zadań</a>
	<li><a href="/?id=ekrsrode" title="Lekcje i rozwiązywanie zadań">Lekcje i rozwiązywanie zadań</a>
	<li><a href="/?id=ekrstart" title="Start - zacznij naukę">Start - czyli zacznij naukę</a>
	<li><a href="/?id=ekrtesty" title="Testy i egzaminy sprawdzające">Testy i egzaminy sprawdzające</a>
	<li><a href="/?id=ekrwzory" title="Wzory definicje i tablice">Wzory definicje i tablice matematyczne</a>
	<li><a href="/?id=ekrzadpp" title="Koniec lekcji - Udzielanie odpowiedzi w pigułce">Koniec lekcji - udzielanie odpowiedzi w pigułce</a>
	<li><a href="/?id=elementy" title="Najciekawsze moduły, podprogramy">Elementy - Najciekawsze moduły, opcje i funkcje</a>
	<li><a href="/?id=instal" title="Instalacja programu">Uruchomienie i instalacja programu</a>
	<li><a href="/?id=mapa" title="Mapa programu gdzie możesz zapoznać się z wyglądem programu Matematyk i jego poszczególnymi modułami">Mapa programu</a>
	<li><a href="/?id=mapa2" title="Główne okno programu">Główne okno programu Matematyk</a>
	<li><a href="/?id=naucz" title="Dla nauczycieli">Dla nauczycieli</a>
	<li><a href="/?id=start" title="Start - zawartość programu">Start - Rozpocznij pracę z programem</a>
	<li><a href="/?id=system" title="Wymagania sprzętowe">Wymagania sprzętowo-programowe</a>
</ul>
</div>