#Jedyny w swoim rodzaju program do nauki Matematyki. Głównym zadaniem Matematyka jest nauczenie Cię matematyki, poprzez samodzielne rozwiązywanie zadań.

<div class="centertext">
    <h1>Matematyka - rozpocznij pracę z programem</h1>
    <img src="/img/chlopek.gif" alt="" width="61" height="81" class="float-left">
    <img src="/img/amflaga.gif" alt="Andrzej ENZAWCA Mazur (AMPartner)" width="51" height="51" class="float-right">

    <p><em><strong>Nie martw się!</strong></em>
    Już ukazał się, jedyny w swoim rodzaju program do nauki
    Matematyki. Nie będzie to kolejna zabawka multimedialna
    - choć multimediów w nim nie brakuje. Nie będzie to
    kolejna prymitywna gra edukacyjna - choć elementów
    rywalizacji w nim nie brakuje. Nie będzie to też
    kolejny program dla nauczycieli - choć i oni znajdą w
    nim dużo informacji dla siebie. </p>
    <h2>Matematyk</h2>
    <p>Głównym zadaniem Matematyka jest nauczenie Cię
    matematyki, poprzez samodzielne rozwiązywanie zadań.</p>
    <p>Program Matematyk spełnia wszelkie wymagania stawiane
    przy nowoczesnym podejściu do matematycznego
    kształcenia dzieci i młodzieży. Zawiera kompletny
    program szkolny nauczania matematyki od klasy IV do VIII
    wraz ze zbiorem zadań egzaminacyjnych do szkół
    średnich.</p>
    <p>Przyjazne środowisko programu Matematyk zachęca do
    samodzielnej nauki reguł matematycznych a kolorowe i
    trafnie dobrane ikony zachęcają nawet najbardziej
    obojętnych użytkowników do współpracy.</p>
    <h2>Przyciski - ikony</h2>
    <p>Podczas pracy z zadaniami masz do dyspozycji
    następujące klawisze:</p>
    <p class=center><img src="/img/ekrmain.gif" alt="Matematyk - główne przyciski" width="317"
    height="372"></p>
    <h2>Rozwiązywanie zadań</h2>
    <p>Po wybraniu interesującej lekcji, jej treść
    zostanie wyświetlona na ekranie. Po zapoznaniu się z
    zadaniem, udzielamy odpowiedzi wpisując wyniki w
    odpowiednie pola:</p>
    <p class=center><img src="/img/zadpole.gif" alt="Zadanie pole" width="277" height="172"></p>
    <p>lub wybierając właściwą odpowiedź odznaczając
    ją wśród dostępnych opcji:</p>
    <p class=center><img src="/img/zadopcja.gif" alt="Zadanie opcja" width="184" height="158"></p>
    <h2>Pomoc w rozwiązywaniu zadań</h2>
    <p>Podczas rozwiązywania zadań możesz przełączyć
    się na <strong>Podręcznik</strong>, jak i na okno
    zawierające rozwiązanie, wskazówki lub <strong>Podpowiedź</strong>.
    </p>
    <!-- kotwica -->
    <a name="idk_testy"></a>
    <h2>Sprawdzenie wiadomości</h2>
    <p>W dowolnym momencie, za pomocą przycisku <strong>Testy</strong>,
    możesz sprawdzić swoją wiedzę rozwiązując testy
    cząstkowe <em>(sprawdziany z poszczególnych klas)</em>,
    lub testy końcowe zawierające całość materiału ze
    szkoły podstawowej.</p>
    <p class=center><img src="/img/test.gif" alt="ekran testy"
    width="476" height="295"></p>
    <h2>To jeszcze nie koniec</h2>
    <p>W programie <em>Matematyk</em>, oprócz rzeczy
    opisanych powyżej, znajdziesz wiele innych ciekawych
    podprogramów spełniających funkcje, uzupełniające i
    rozszerzające materiał zawarty w głównej części
    programu. Pozwalają one w nieco bardziej zabawowy
    sposób zapoznawać się z matematyką. Dostęp do tych
    funkcji realizowany jest przez przyciski.</p>
    <p class=center><a href="/?id=elementy"><img src="/img/ekreleme.gif" alt="Najciekawsze moduły, podprogramy" width="416" height="103"></a></p>
    <p>Na opis znajdujących się tam modułów zapraszam pod
    przycisk <a href="/?id=elementy">Elementy - najciekawsze moduły</a>.</p>
    <p>Wszystkich zainteresowanych stroną techniczną programu,
    zapraszam pod następujące odsyłacze:</p>
    <ul class="mini">
        <li><a href="/?id=system">Wymagania sprzętowo-programowe</a></li>
        <li><a href="/?id=instal">Instalacja programu</a></li>
    </ul>

    <p class="center">
    <img src="/img/kulnieb.gif" hspace="10"
    width="12" height="12"><img src="/img/kulnieb.gif" hspace="10"
    width="12" height="12"><img src="/img/kulnieb.gif" hspace="10"
    width="12" height="12"></p>
</div>
