#Wymagania sprzętowe programu - System operacyjny, Procesor, Pamięć, Przestrzeń dyskowa, Urządzenia peryferyjne

<div class="centertext">
    <h1>Wymagania sprzętowe programu</h1>

    <h2>System operacyjny:</h2>
	<img src="/img/mlotek.gif" width="108" height="100" class="float-left" style="margin-top: -10px" alt="Wymagania sprzętowe">
	<img src="/img/amflaga.gif" width="51" height="51" class="float-right" alt="EZNAWCA (AMstudio)">
    <ul class="mini">
        <li>DOS 5.0 lub nowszy,</li>
        <li>Windows 3.1x + DOS 5.0 lub nowszy,</li>
        <li>Windows 95/98,</li>
        <li>Windows 2000 Professional.</li>
    </ul>
    <h2 style="clear:both">Procesor:</h2>
    <ul class="mini">
        <li>486DX 40MHz lub lepszy <em>(zalecane: Pentium 75MHz lub lepszy).</em></li>
    </ul>
    <h2>Pamięć:</h2>
    <ul class="mini">
        <li>2MB RAM <em>(ok. <strong>520</strong>KB pamięci konwencjonalnej i <strong>1</strong>MB pamięci rozszerzonej <strong>XMS</strong>)</em>,</li>
        <li>Przy pracy z Windows odpowiednio więcej:</li>
        <li>Windows 3.1x: 4MB,</li>
        <li>Windows 95/98: 8MB <em>(zalecane 12MB)</em>.</li>
            <li>Windows 2000 Pro: 32MB (zalecane 64MB)</li>
    </ul>
    <h2>Przestrzeń dyskowa:</h2>
    <ul class="mini">
        <li>300KB (lub mniej) wolnego miejsca na dysku C:,</li>
    </ul>
    <h2>Urządzenia peryferyjne:</h2>
    <ul class="mini">
        <li>Czytnik dysków CDROM <strong>8xSpead</strong> lub
            szybszy <em>(niezbędny - program pracuje
            bezpośrednio z płyty CDROM; możliwa jest praca
            z CDROM'em 4xSpead i 2xSpead, ale podczas pracy
            mogą występować pewne nieprawidłowości)</em>.</li>
        <li>Myszka (lub Trackbal itp.),</li>
    </ul>
    <h3>Zalecane:</h3>
    <ul class="mini">
        <li>Monitor kolorowy,</li>
        <li>Karta dźwiękowa zgodna z SoundBlaster,</li>
    </ul>
    <h2>Ustawienia systemowe:</h2>
    <ul class="mini">
        <li>Zwolnione jak najwięcej pamięci konwencjonalnej,</li>
        <li>Dostępne co najmniej <strong>1024</strong>KB pamięci <strong>XMS</strong> <em>(extended, a nie pamięci EMS-expanded)</em>,</li>
    </ul>
    <h3>Zalecane:</h3>
    <ul class="mini">
        <li>Poprawnie zdefiniowana zmienna <strong>TEMP</strong> w <strong>AUTOEXEC.BAT</strong>, np:<br>
            <code>set TEMP=C:\WINDOWS\TEMP</code></li>
        <li>Poprawnie zdefiniowana zmienna <strong>BLASTER</strong>, ułatwiająca identyfikację karty dźwiękowej SoundBlaster.</li>
    </ul>

    <p class=center>
    <img src="kulnieb.gif" hspace="10" width="12" height="12">
    <img src="kulnieb.gif" hspace="10" width="12" height="12">
    <img src="kulnieb.gif" hspace="10" width="12" height="12">
    </p>
</div>