<h2>Treść i materiały dydaktyczne</h2>
dr Maria Kruk<br>
Andrzej Domaradzki<br>
Andrzej Mazur<br>
Paweł Grabowski<br>
<br>

<h2>Weryfikacja materiałów</h2>
dr Maria Kruk<br>
Joanna Dudek<br>
Anna Gadomska<br>
Andrzej Mazur<br>
<br>

<h2>Animacje</h2>
Sylwester Gigoń<br>
Andrzej Kukuła<br>
Dawid Kliszewski<br>
Wojciech Pukocz<br>
<br>

<h2>Oprawa dźwiękowa</h2>
Radosław Szamrej<br>
Adam Skorupa<br>
<br>

<h2>Głosy</h2>
Danuta Dudek<br>
Mirella Pempko<br>
Anna Mazur<br>
<br>

<h2>Konsultacje</h2>
Zespół nauczycieli matematyki<br>
Kuratorium Oświaty we Wrocławiu<br>
<br>

<h2>Producent</h2>
FATERBIT A.P.H.<br>
Marcin Dudek<br>
tel. (0-71) 3134108<br>
e-mail: <a href="mailto:biuro@faterbit.com.pl">biuro@faterbit.com.pl</a><br>
e-mail: <a href="mailto:faterbit@polbox.com">faterbit@polbox.com</a><br>
<br>
<h2>Wyłączny dystrybutor</h2>
JONASOFT<br>
