<section class="row">
	<div class="col-lg-9">
		<h1 class="mb-4">Polityka prywatności</h1>

		<h2 class="h4 mt-4">Dane osobowe</h2>
		<p>W czasie korzystania z witryny <u>Eznawca.pl</u> możesz zostać poproszony o podanie niektórych danych osobowych (np. poprzez wypełnienie formularza kontaktowego). <u>Eznawca.pl</u> nigdy, pod żadnym pozorem, nie udostępnia danych kontaktowych swoich użytkowników osobom ani firmom trzecim.</p>

		<h2 class="h4 mt-4">Ciasteczka (cookies)</h2>
		<p>Witryna <u>Eznawca.pl</u> wykorzystuje ciasteczka (cookies), czyli małe pliki tekstowe wysyłane do urządzenia odwiedzającego, identyfikujące go w sposób potrzebny do uproszczenia i przyspieszenia działania serwisu. Ciasteczka są nieszkodliwe dla urządzenia i stanowią standardową usługę udostępnianą przez wszystkie przeglądarki internetowe. Każdy użytkownik może je wyłączyć w ustawieniach własnej przeglądarki.</p>
		<p>Aby zarządzać ustawieniami cookies, wybierz z listy poniżej swoją przeglądarkę i postępuj zgodnie z instrukcjami:</p>
		<ul>
			<li><a href="https://support.microsoft.com/pl-pl/help/4027947/microsoft-edge-delete-cookies" target="_blank" rel="nofollow noopener">Microsoft Edge</a></li>
			<li><a href="https://support.google.com/chrome/answer/95647" target="_blank" rel="nofollow noopener">Chrome</a></li>
			<li><a href="https://support.apple.com/pl-pl/guide/safari/sfri11471/mac" target="_blank" rel="nofollow noopener">Safari</a></li>
			<li><a href="https://support.mozilla.org/pl/kb/wzmocniona-ochrona-przed-sledzeniem-firefox-desktop" target="_blank" rel="nofollow noopener">Mozilla Firefox</a></li>
			<li><a href="https://help.opera.com/pl/latest/web-preferences/#cookies" target="_blank" rel="nofollow noopener">Opera</a></li>
		</ul>

		<h2 class="h4 mt-4">Rodzaje cookies</h2>
		<ul>
			<li><strong>Sesyjne</strong> - pliki tymczasowe przechowywane do czasu opuszczenia strony lub wyłączenia przeglądarki.</li>
			<li><strong>Stałe</strong> - przechowywane przez zadany okres lub do czasu ich usunięcia przez użytkownika.</li>
		</ul>

		<h2 class="h4 mt-4">Google Analytics</h2>
		<p><u>Eznawca.pl</u> może korzystać z Google Analytics - usługi analizy oglądalności stron udostępnianej przez Google. Google Analytics używa cookies w celu przeanalizowania, w jaki sposób użytkownicy korzystają z witryny. Informacje te służą do oceny korzystania z witryny oraz tworzenia raportów dotyczących ruchu na stronach.</p>

		<h2 class="h4 mt-4">Wyłączenie odpowiedzialności</h2>
		<p>Autor serwisu dołożył wszelkich starań, aby treści były rzetelne, nie ponosi jednak odpowiedzialności za treści opinii i komentarzy osób trzecich publikowanych w serwisie.</p>

		<h2 class="h4 mt-4">Więcej informacji</h2>
		<p>Więcej o plikach cookies znajdziesz na stronie: <a href="https://pl.wikipedia.org/wiki/Ciasteczko" target="_blank" rel="nofollow noopener">pl.wikipedia.org/wiki/Ciasteczko</a>.</p>
	</div>
</section>
